version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      IMAGE_NAME: chamopower/laravel-kubernetes-demo
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: 'Create env file'
          command: |
            echo -e 'APP_NAME="Laravel"' > .env
            echo -e 'APP_ENV=production' >> .env
            echo -e 'APP_KEY='${APP_KEY} >> .env
            echo -e 'APP_DEBUG=false' >> .env
            echo -e 'LOG_CHANNEL="daily"' >> .env
            echo -e 'DB_CONNECTION="mysql"' >> .env
            echo -e 'DB_HOST="'${DB_HOST}'"' >> .env
            echo -e 'DB_PORT="'${DB_PORT}'"' >> .env
            echo -e 'DB_DATABASE="'${DB_DATABASE}'"' >> .env
            echo -e 'DB_USERNAME="'${DB_USERNAME}'"' >> .env
            echo -e 'DB_PASSWORD="'${DB_PASSWORD}'"' >> .env
            echo -e 'BROADCAST_DRIVER=log' >> .env
            echo -e 'CACHE_DRIVER=file' >> .env
            echo -e 'QUEUE_CONNECTION=sync' >> .env
            echo -e 'SESSION_DRIVER=file' >> .env
            echo -e 'SESSION_LIFETIME=120' >> .env        
      - run:
          name: Setup nova repository authentication
          command: |
            echo "{\"http-basic\":{\"nova.laravel.com\":{\"username\":\"${NOVA_USERNAME}\",\"password\":\"${NOVA_PASSWORD}\"}}}" > auth.json
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_SHA1
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$CIRCLE_SHA1
      - run:
          name: Install envsubst
          command: |
            sudo apt-get update && sudo apt-get -y install gettext-base
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod u+x ./kubectl
      - run:
          name: Deploy Code
          command: ./scripts/ci-deploy.sh            
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
